### ISSUE TITLE
Where is irma-probe-app-1.1.0.tar.gz located?

### ISSUE THREAD

**Issue by bedazzlinghex** [quarkslab/irma#22]
Hi,

I am using the finished virtual machine (1.3.2) that is available on the website and I am trying to configure a seperate probe. I have followed the installation instructions to the letter and cloned the repository, but when it comes to this line:

pip install irma-probe-app-1.1.0.tar.gz --install-option="--install-base=/opt/irma/irma-probe"

This files does not exsist anywhere inside the irma-probe repo? Am I missing something? Where is this file supposed to be located?

Appreciate any help in this matter.

**Comment by ch0k0bn** [comment]
you don't need this (outdated) command anymore. If you've downloaded the virtual appliance the irma-probe app code is already here (under /opt/irma/irma-probe/current directory).

Check this blogpost http://blog.quarkslab.com/writing-our-own-analyzer-for-the-open-source-multi-scanner-irma.html, begin at this point "Writing a Module for the TrID Utility" as you already have a running instance.
