### ISSUE TITLE
module Kaspersky 17.0 avp

### ISSUE THREAD

**Issue by dubierthomas** [quarkslab/irma#27]
line 186 in file probe/modules/antivirus/base.py
if paths.lower() in filename or\
       os.path.relpath(paths.lower()) in filename:
                ....
Kaspersky output : 
2016-12-13 15:02:38         c:\users\irmaprobe\appdata\local\temp\tmpi0plfn detected        EICAR-Test-File

filename ---> "c:\users\irmaprobe\appdata\local\temp\tmpi0plfn"
but paths equals "c:\users\irmapr~1\appdata\local\temp\tmpi0plfn"

**Comment by ch0k0bn** [comment]
nice spot, as our user is always "vagrant" we never saw it happen.

**Comment by iarce-qb** [comment]
stale bug
probe is deprecated
