### ISSUE TITLE
Report

### ISSUE THREAD

**Issue by rmsferreira** [quarkslab/irma#31]
Hi all,
is possible to add a report module to export the results to xml for example.

Thanks.

**Comment by ch0k0bn** [comment]
Hi, nothing is planned for exporting a report shortly. 
Our first idea was to have a webview, formatted for printing.
If you want something specific, you better have to build something based on the results json from the web api.

**Comment by ch0k0bn** [comment]
In IRMA v2.1 we added a csv report feature, it is still possible to have the json result to customize it.
