### ISSUE TITLE
Kaspersky Endpoint Security 10 

### ISSUE THREAD

**Issue by 1623664** [quarkslab/irma#36]
Kaspersky Endpoint Security 10 outputs the result "clean" in the Web, although the Probe detection is. Where am I wrong?

**Comment by ch0k0bn** [comment]
does it ship with avp.com commandline executable ?
We use Kaspersky antivirus 16 or 17. You could download trial version there: https://www.kaspersky.com/downloads/thank-you/antivirus-free-trial

**Comment by 1623664** [comment]
As I understand it support for Kaspersky endpoint security 10, no?((

**Comment by ch0k0bn** [comment]
Development was made on Kaspersky Internet Security, but for licence cost  we moved to Kaspersky Antivirus. Never tried with Endpoint Security.

**Comment by 1623664** [comment]
Yes indeed the problem was this, sorry keys are not suitable(( might try to improve it?

**Comment by 1623664** [comment]
Tell me to limit Drweb? Version Drweb 10.1.0.0.1505251940, the same problem that Kaspersky Endpoint Security

**Comment by ch0k0bn** [comment]
not planned sorry.
