### ISSUE TITLE
report object in JSON

### ISSUE THREAD

**Issue by razuz** [quarkslab/irma#40]
Hi,

would it make sense for you guys to have report object unified to string across all probes and in case additional data is available then save it in another object (for example report_data) ?
Background behind that is when I roll over all probe_results then I get to a point where normally results value is always a string. However PE results gives a JSON object back. Therefore it gets quite complicated to save the result to Elasticsearch as there is no unified mapping to be created so it will always be a workaround :/
Case where I bumped into it was : https://github.com/cuckoosandbox/cuckoo/issues/1217

Cheers,
razu

**Comment by ch0k0bn** [comment]
done in APIv2 defaul output for results is dict now no longer list
[code](https://github.com/quarkslab/irma/blob/master/frontend/api/files_ext/models.py#L154)
