### ISSUE TITLE
"/opt/sophos-av/bin/savscan --version"  "[Errno 2] No such file or directory"

### ISSUE THREAD

**Issue by icepaule** [quarkslab/irma#43]
Hi quarkslab,

the **VM_ENV=dev vagrant provision** (TASK [quarkslab.sophos : Sophos | Check installed version]) fails with above error message but it is installed and at the correct place.

root@ubuntu:/opt/irma/ansible# **/opt/sophos-av/bin/savscan --version**
SAVScan virus detection utility
Copyright (c) 1989-2017 Sophos Limited. All rights reserved.

System time 10:17:51 AM, System date 15 December 2017

Product version           : 5.38.0
Engine version            : 3.69.2
Virus data version        : 5.41
User interface version    : 2.03.069
Platform                  : Linux/AMD64
Released                  : 27 June 2017
Total viruses (with IDEs) : 13603638

Next error is:
TASK [quarkslab.sophos : Sophos | Download installation archive] 
fatal: [avs-linux.irma]: FAILED! => {"changed": false, "dest": "**/tmp/sophos/sav-linux.tgz**", "failed": true, "msg": "Request failed", "response": "HTTP Error 404: Not Found", "state": "absent", "status_code": 404, "url": "http://downloads.sophos.com/XXXX"}

I've also placed the renamed original file at above destination.

root@ubuntu:/opt/irma/ansible# ls -l /tmp/sophos/sav-linux.tgz
-rw-r--r-- 1 root root 539920492 Dec 15 10:01 **/tmp/sophos/sav-linux.tgz**

Could you please help me?  :-)

Thanks a lot and have a nice weekend.
Marcus

**Comment by ch0k0bn** [comment]
You should just update the download  [link](https://github.com/quarkslab/irma/blob/master/ansible/roles/quarkslab.sophos/defaults/main.yml#L5)
for ansible to have a valid url (as it is temporary link we are not able to put a valid one)
