### ISSUE TITLE
authentication failure

### ISSUE THREAD

**Issue by sam-23** [quarkslab/irma#44]
Activating analyzer
1)  sudo su irma 
2)  cd /opt/irma/irma -probe/current/
3) venv/bin/pip install -r \ modules/external/virustotal/requirements.txt

At step 3 error occurred and it says permission denied when step 3 is executed.
how to access the root and need the root password 
I have imported the Irma 1.5.3 .ova file.
It need the password for sudo su  irma ?

**Comment by ch0k0bn** [comment]
to install new stuff on the virtual machine use the `deploy` account (that has sudo rights).
```
sudo su deploy
cd /opt/irma/irma -probe/current/
venv/bin/pip install -r modules/external/virustotal/requirements.txt
```
Btw use the 2.0 ova if you want something newer
