### ISSUE TITLE
Update service.py

### ISSUE THREAD

**Issue by r00t0vi4** [quarkslab/irma#45]
Python 3.5 does not support multiprocessing.forking and ConfigParser modules.

Original script was updated for Python 3+
https://github.com/antoinemartin/django-windows-tools/blob/master/django_windows_tools/service.py

Can you update your script, please.
https://github.com/quarkslab/irma/blob/master/probe/extras/winsrv/service.py

**Comment by ch0k0bn** [comment]
This code is no longer used directly by automated install (explaining why we missed that during testing phase). Thx for the feedback,
