### ISSUE TITLE
Quarkslab box not found

### ISSUE THREAD

**Issue by seantree** [quarkslab/irma#47]
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'quarkslab/debian-9.0.0-amd64' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: 20180312
The box 'quarkslab/debian-9.0.0-amd64' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/quarkslab/debian-9.0.0-amd64"]
Error: The requested URL returned error: 404 Not Found
****

**Comment by ch0k0bn** [comment]
box latest version for virtualbox is [v201802220](https://app.vagrantup.com/quarkslab/boxes/debian-9.0.0-amd64/versions/20180220).
Without any version specified vagrant should download this one. If you have set a particular version in your ``environment file`` or in ``Vagrantfile`` could you please remove it and try again ?

If you are updating from a previous environment or using an old version of vagrant, you are maybe affected by this [bug](https://github.com/hashicorp/vagrant/issues/9442#issuecomment-363126830) and you could try the suggested workaround or updating vagrant.

**Comment by seantree** [comment]
Hi @ch0k0bn 

same problem I am facing again

sudo vagrant up
172.16.1.30
Bringing machine 'brain.irma' up with 'virtualbox' provider...
==> brain.irma: Box 'quarkslab/debian-9.0.0-amd64' could not be found. Attempting to find and install...
    brain.irma: Box Provider: virtualbox
    brain.irma: Box Version: >= 0
The box 'quarkslab/debian-9.0.0-amd64' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/quarkslab/debian-9.0.0-amd64"]
Error: The requested URL returned error: 404 Not Found

**Comment by seantree** [comment]
Now after fixing the above problem by upgrading the vagrnat I am facing the below issue:

TASK [setup] *******************************************************************
2018-03-19T10:04:24.453688 (delta: 0.212292)         elapsed: 0.214935 ******** 
fatal: [brain.irma]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Connection timed out during banner exchange\r\n", "unreachable": true}

PLAY RECAP *********************************************************************
brain.irma                 : ok=0    changed=0    unreachable=1    failed=0   

2018-03-19T10:06:29.119054 (delta: 124.665333)         elapsed: 124.880301 **** 
=============================================================================== 
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by ch0k0bn** [comment]
it seems to be vbox related. Try to boot it again and see in Virtualbox gui the status of the vm. Check also the virtual network status.
Recent tests was done with vbox5 i dont know which version/OS do you run.

**Comment by ch0k0bn** [comment]
any updates on your issue ?

**Comment by seantree** [comment]
now I am getting different errors :(
