### ISSUE TITLE
Scripts are not working

### ISSUE THREAD

**Issue by techchetn** [quarkslab/irma#50]
Hi,

From the Brian configuration 
 $ cd /opt/irma/irma-brain/current/
$ ./venv/bin/python -m scripts.create_user 

scripts are not working and couldn't find the scripts anywhere, can you help ?

**Comment by ch0k0bn** [comment]
Could you check that the file 

> /opt/irma/irma-brain/current/scripts/create_user.py

exists. It should as it is a copy of brain src code:

https://github.com/quarkslab/irma/blob/master/brain/scripts/create_user.py

**Comment by techchetn** [comment]
It gave me No module named config.parser error

**Comment by ch0k0bn** [comment]
you should launch the command from ``/opt/irma/irma-brain/current/`` directory
something like:
```
python -m scripts.create_user
```

Look how it's done in automatic install [here](https://github.com/quarkslab/irma/blob/master/ansible/roles/quarkslab.irma_deployment_brain/tasks/main.yml#L50)

**Comment by techchetn** [comment]
Same error

bimmer@IRMA:/opt/irma/irma-brain/current$ sudo python -m scripts.create_user/usr/bin/python: No module named scripts
bimmer@IRMA:/opt/irma/irma-brain/current$ sudo ./venv/bin/python -m scripts.create_user frontend mqfrontend frontend
/opt/irma/irma-brain/current/venv/bin/python: No module named scripts
bimmer@IRMA:/opt/irma/irma-brain/current$

**Comment by ch0k0bn** [comment]
coud you connect to IRC #qb_irma@freenode ? will be easier to debug

**Comment by techchetn** [comment]
Hey ch0k0bn, please let me know if you are online

**Comment by techchetn** [comment]
Hey, can we do this today ?

**Comment by ch0k0bn** [comment]
yes, online for next 3 hours

**Comment by techchetn** [comment]
I'm online and joined qb_irma@freenode

**Comment by techchetn** [comment]
Anyone online please let me know, thanks!

**Comment by ch0k0bn** [comment]
Yes I am online

**Comment by techchetn** [comment]
same IRC ?

**Comment by ch0k0bn** [comment]
same

**Comment by techchetn** [comment]
Have you joined IRC ?

**Comment by ch0k0bn** [comment]
i'm on it but dont see you. Could you try https://webchat.freenode.net/ then join #qb_irma ?
