### ISSUE TITLE
Refreshing probe list return an empty list

### ISSUE THREAD

**Issue by PostNoctem** [quarkslab/irma#53]
Hello guys,

I am tryharding to make IRMA work more than one day.

Indeed, it is working only less than 24h in a row, then the probe list is randomly emptied because brain and probes do not communicate anymore.

All my supervisor tasks are in debug mode, but I have no logs explaining why the connection between probes and brain is timed out.

Here is an example of brain supervisor.log showed.
[brain log.txt](https://github.com/quarkslab/irma/files/2265799/brain.log.txt)

If you have an idea of where I can find the origin of the issue... Thank you.

**Comment by ch0k0bn** [comment]
This seems to be purely rabbitmq related, brain is looking for active queues and detects none, You should see why probes are no longer connected to the rabbitmq server, by activating debug.

You could also try rabbitmqctl commands to see active queues and see if probes are connected or not.

btw supervisord is no longer used in IRMA (we swiched to systemd recently) but it does not help for your problem

**Comment by PostNoctem** [comment]
I guess it is from rabbitmq indeed. 
I put the debug mode on, tried the web interface of rabbitmq and spied the logs. All looks great except a single line in my syslog:
WARNING:celery.worker.consumer:consumer: Connection to broker lost. Trying to re-establish the connection...

But il looks like it never reconnects. 
I do not know where to investigate :)

**Comment by PostNoctem** [comment]
Addresses are okay as celery checks :/
The probes are connected once, then randomly times-out and cannot re-connect anymore.
