### ISSUE TITLE
Analyze big file with IRMA 

### ISSUE THREAD

**Issue by Inlol4** [quarkslab/irma#57]
Hi guys,
I got a problem when i scan big file (between 200MO and 1 GO) with IRMA.
The log file tells me its an error 413, a Request Entity Too Large error.
So i deactivate the functionality in frontend and frontend-https with the option :

 client_max_body_size 0.

But i still get an error 413. What do i miss ?

**Comment by ch0k0bn** [comment]
Hello,

It seems nginx related, have you changed this line:
https://github.com/quarkslab/irma/blob/master/ansible/playbooks/group_vars/frontend.yml#L198
and launched again the nginx provisioning ?

If so could you double-ckeck in the nginx config ``/etc/nginx/sites-enabled/irma-frontend.conf`` file that it is the correct value and also that nginx has been correctly restarted.

**Comment by Inlol4** [comment]
oh my god that was just that, i was too focus on the files in /opt/irma/irma-frontend , that i miss this one.
Thank you, like you said i changed the value and that worked .
Thank you again
