### ISSUE TITLE
Setting up IRMA

### ISSUE THREAD

**Issue by Asarewin** [quarkslab/irma#58]
Hello,

i've tried setting up IRMA the easiest way,

everything goes right until i want to see the frontend interface of irma i saw in a previous issue that i need to setup irma-frontend and i'd love to but it seems that the command : 

python irma-ansible.py environments/allinone_prod.yml playbooks/playbook.yml

it cannot find irma-ansible.py and the shortcut seems broken,
is the command i put above the one that will setup irma frontend ?
could i have some insight on what to do to fix this ?

Thank you

**Comment by ch0k0bn** [comment]
irma-ansible is a submodule of irma, if you have not clone this directory with `--recursive` you may have missed it. In that case just enter in your irma repo local copy:
```
git submodule init
git submodule update
```
and irma-ansible should be fetched and available

**Comment by ch0k0bn** [comment]
Production mode is meant to be run from a packaged archive (you could not guess it and its not (yet) written in the doc, sorry for that).
packaged archive is generated with setup.py and embed the proper version of the code (based on the commit) and an archive with the UI already built (the missing `core-webui-HEAD.zip` file in your error).

To solve your problem, the easiest way is to build locally the UI (it requires nodejs)
```
$ cd frontend/web
$ npm install
$ ./node_modules/.bin/bower  update
$ ./node_modules/.bin/gulp dist
```
UI is now built inside `dist`directory
then create an archive with `dist` directory (archive must contains dist directory not only the file inside `dist` as we will later deploy it directly inside `frontend/web` and the `dist` directory is in the UI path.)

```
zip -r ../../ansible/playbooks/files/core-webui-HEAD.zip dist/
```
now you could retry irma-ansible command as you have the missing UI file.

**Comment by Asarewin** [comment]
Oh OK so the doc is not complete that would explain why I bump into so much errors thanks for the explanation. 

Say I want to install Irma the easy way, could you give me a complete rundown of what I need to do?
I will use Irma as part of my studies project and the doc not being complete and me being a student is not really helping unfortunately. 

I would love for you to do that if that's not asking too much from you of course
