### ISSUE TITLE
error during ansible setup

### ISSUE THREAD

**Issue by shellchocolat** [quarkslab/irma#62]
Hello, 

I got an error while setting up ansible (prod):
`python irma-ansible.py environments/allinone_prod.yml playbooks/playbook.yml`

The errors are:
`
TASK [ANXS.postgresql : PostgreSQL | Make sure the dependencies are installed] ************
2019-05-22T11:31:33.799812 (delta: 1.529815)         elapsed: 54.781102 ******* 
failed: [brain.irma] (item=[u'python-psycopg2', u'python-pycurl', u'locales']) => {"changed": false, "item": ["python-psycopg2", "python-pycurl", "locales"], "msg": "Failed to update apt cache."}

PLAY RECAP ********************************************************************************
brain.irma                 : ok=41   changed=6    unreachable=0    failed=1   
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
`

Also, python-psycopg2, python-pycurl and locales are well installed.

Any idea?

**Comment by ch0k0bn** [comment]
this step force a cache refresh https://github.com/quarkslab/postgresql/blob/master/tasks/install.yml#L38
and it has failed, if you retry it, do you have the same issue ? if yes could you try it with verbose enabled (`-vvv` at the end of `irma-ansible.py` command)

**Comment by shellchocolat** [comment]
Hello, 
Still not working after a retry.
With verbose mode enabled, logs are:
`irma-ansible.py:38: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.config = yaml.load(f.read())
[+] Ansible vars written to /tmp/tmppA1nJm/vars.yml
[+] Ansible inventory written to /tmp/tmppA1nJm/inventory
[+] launching ansible-galaxy
- changing role ANXS.postgresql from cec55c974e6020044ef908e2acca9377d470b473 to cec55c974e6020044ef908e2acca9377d470b473
- extracting ANXS.postgresql to /home/raton/irma/ansible/roles/ANXS.postgresql
- ANXS.postgresql (cec55c974e6020044ef908e2acca9377d470b473) was installed successfully
- changing role franklinkim.sudo from 1.6.1 to 1.6.1
- extracting franklinkim.sudo to /home/raton/irma/ansible/roles/franklinkim.sudo
- franklinkim.sudo (1.6.1) was installed successfully
- changing role franklinkim.ufw from 1.6.0 to 1.6.0
- extracting franklinkim.ufw to /home/raton/irma/ansible/roles/franklinkim.ufw
- franklinkim.ufw (1.6.0) was installed successfully
- changing role jdauphant.nginx from v2.7.4 to v2.7.4
- extracting jdauphant.nginx to /home/raton/irma/ansible/roles/jdauphant.nginx
- jdauphant.nginx (v2.7.4) was installed successfully
- changing role Mayeu.RabbitMQ from 30ba105a753bb21eed07c8fa4b2635ff297b54b9 to 30ba105a753bb21eed07c8fa4b2635ff297b54b9
- extracting Mayeu.RabbitMQ to /home/raton/irma/ansible/roles/Mayeu.RabbitMQ
- Mayeu.RabbitMQ (30ba105a753bb21eed07c8fa4b2635ff297b54b9) was installed successfully
- changing role mivok0.users from v1.2.4 to v1.2.4
- extracting mivok0.users to /home/raton/irma/ansible/roles/mivok0.users
- mivok0.users (v1.2.4) was installed successfully
- changing role willshersystems.sshd from v0.4.7 to v0.4.7
- extracting willshersystems.sshd to /home/raton/irma/ansible/roles/willshersystems.sshd
- willshersystems.sshd (v0.4.7) was installed successfully
[+] launching ansible-playbook
[DEPRECATION WARNING]: The use of 'include' for tasks has been deprecated. Use 'import_tasks' for static inclusions or 'include_tasks' for dynamic inclusions. This feature will be 
removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: include is kept for backwards compatibility but usage is discouraged. The module documentation details page may explain more about this rationale.. This feature
 will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

PLAY [all] *****************************************************************************************************************************************************************************
2019-05-29T05:31:42.236015 (delta: 0.006768)         elapsed: 0.006768 ******** 
=============================================================================== 

TASK [Gathering Facts] *****************************************************************************************************************************************************************
2019-05-29T05:31:42.310075 (delta: 0.074032)         elapsed: 0.080828 ******** 
fatal: [brain.irma]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: connect to host 172.16.1.30 port 22: Connection timed out\r\n", "unreachable": true}

TASK [Check ansible version] ***********************************************************************************************************************************************************
2019-05-29T05:32:26.582057 (delta: 44.271952)         elapsed: 44.35281 ******* 
ok: [localhost -> localhost] => {
    "changed": false, 
    "msg": "All assertions passed"
}
 [WARNING]: Could not match supplied host pattern, ignoring: windows


PLAY [Common tasks to execute on all Linux servers] ************************************************************************************************************************************
2019-05-29T05:32:26.604834 (delta: 0.02275)         elapsed: 44.375587 ******** 
=============================================================================== 

PLAY [Manage infra files] **************************************************************************************************************************************************************
2019-05-29T05:32:26.619026 (delta: 0.014146)         elapsed: 44.389779 ******* 
=============================================================================== 

TASK [quarkslab.local_manage_infra : Check if infra name has been provided by user] ****************************************************************************************************
2019-05-29T05:32:26.627569 (delta: 0.008528)         elapsed: 44.398322 ******* 
skipping: [localhost]

TASK [quarkslab.local_manage_infra : Check if infra data file exists] ******************************************************************************************************************
2019-05-29T05:32:26.641927 (delta: 0.014334)         elapsed: 44.41268 ******** 
skipping: [localhost]

TASK [quarkslab.local_manage_infra : Create root] **************************************************************************************************************************************
2019-05-29T05:32:26.656416 (delta: 0.014457)         elapsed: 44.427169 ******* 
skipping: [localhost]

TASK [quarkslab.local_manage_infra : Create infra data folders for RabbitMq] ***********************************************************************************************************
2019-05-29T05:32:26.672971 (delta: 0.016526)         elapsed: 44.443724 ******* 
skipping: [localhost] => (item=../infras/Qb/pki/rabbitmq/ca) 
skipping: [localhost] => (item=../infras/Qb/pki/rabbitmq/server) 
skipping: [localhost] => (item=../infras/Qb/pki/rabbitmq/clients) 

TASK [quarkslab.local_manage_infra : Create infra data folders for HTTPS] **************************************************************************************************************
2019-05-29T05:32:26.703634 (delta: 0.030634)         elapsed: 44.474387 ******* 
skipping: [localhost] => (item=../infras/Qb/pki/https/ca) 
skipping: [localhost] => (item=../infras/Qb/pki/https/server) 
skipping: [localhost] => (item=../infras/Qb/pki/https/clients/revoked) 

TASK [quarkslab.local_manage_infra : Create infra data folders for PSQL] ***************************************************************************************************************
2019-05-29T05:32:26.732125 (delta: 0.028454)         elapsed: 44.502878 ******* 
skipping: [localhost] => (item=../infras/Qb/pki/psql/ca) 
skipping: [localhost] => (item=../infras/Qb/pki/psql/server) 
skipping: [localhost] => (item=../infras/Qb/pki/psql/clients/revoked) 

TASK [quarkslab.local_manage_infra : Create new infra data file] ***********************************************************************************************************************
2019-05-29T05:32:26.761051 (delta: 0.028889)         elapsed: 44.531804 ******* 
skipping: [localhost]

TASK [quarkslab.local_manage_infra : Generate root] ************************************************************************************************************************************
2019-05-29T05:32:26.777619 (delta: 0.016537)         elapsed: 44.548372 ******* 
skipping: [localhost]

TASK [quarkslab.local_manage_infra : Generate HTTPS PKI] *******************************************************************************************************************************
2019-05-29T05:32:26.793916 (delta: 0.016262)         elapsed: 44.564669 ******* 
skipping: [localhost]

TASK [quarkslab.local_manage_infra : Generate RabbitMq PKI] ****************************************************************************************************************************
2019-05-29T05:32:26.809056 (delta: 0.015103)         elapsed: 44.579809 ******* 
skipping: [localhost]

TASK [quarkslab.local_manage_infra : Generate PSQL PKI] ********************************************************************************************************************************
2019-05-29T05:32:26.826781 (delta: 0.017692)         elapsed: 44.597534 ******* 
skipping: [localhost]

TASK [quarkslab.local_manage_infra : Get input data from '../infras/Qb/Qb-infra.yml'] **************************************************************************************************
2019-05-29T05:32:26.844514 (delta: 0.017702)         elapsed: 44.615267 ******* 
skipping: [localhost]

TASK [quarkslab.local_manage_infra : include_tasks] ************************************************************************************************************************************
2019-05-29T05:32:26.862075 (delta: 0.017529)         elapsed: 44.632828 ******* 
skipping: [localhost]

TASK [quarkslab.local_manage_infra : include_tasks] ************************************************************************************************************************************
2019-05-29T05:32:26.878660 (delta: 0.016551)         elapsed: 44.649413 ******* 
skipping: [localhost]

PLAY [SQL server provisioning] *********************************************************************************************************************************************************
2019-05-29T05:32:26.893076 (delta: 0.014372)         elapsed: 44.663829 ******* 
=============================================================================== 

PLAY [Frontend provisioning] ***********************************************************************************************************************************************************
2019-05-29T05:32:26.917892 (delta: 0.024784)         elapsed: 44.688645 ******* 
=============================================================================== 

PLAY [Brain provisioning] **************************************************************************************************************************************************************
2019-05-29T05:32:26.933075 (delta: 0.015162)         elapsed: 44.703828 ******* 
=============================================================================== 

PLAY [Probe provisioning] **************************************************************************************************************************************************************
2019-05-29T05:32:26.948014 (delta: 0.014923)         elapsed: 44.718767 ******* 
=============================================================================== 

PLAY [ClamAV provisioning] *************************************************************************************************************************************************************
2019-05-29T05:32:26.957290 (delta: 0.009254)         elapsed: 44.728043 ******* 
=============================================================================== 

PLAY [ComodoCAVL provisioning] *********************************************************************************************************************************************************
2019-05-29T05:32:26.960425 (delta: 0.003122)         elapsed: 44.731178 ******* 
=============================================================================== 
 [WARNING]: Could not match supplied host pattern, ignoring: sophos


PLAY [Sophos provisioning] *************************************************************************************************************************************************************
2019-05-29T05:32:26.963756 (delta: 0.003317)         elapsed: 44.734509 ******* 
=============================================================================== 
skipping: no hosts matched
 [WARNING]: Could not match supplied host pattern, ignoring: eset-file-security


PLAY [EsetFileSecurity provisioning] ***************************************************************************************************************************************************
2019-05-29T05:32:26.964777 (delta: 0.001009)         elapsed: 44.73553 ******** 
=============================================================================== 
skipping: no hosts matched
 [WARNING]: Could not match supplied host pattern, ignoring: mcafee


PLAY [McAfee VSCL provisioning] ********************************************************************************************************************************************************
2019-05-29T05:32:26.965791 (delta: 0.001)         elapsed: 44.736544 ********** 
=============================================================================== 
skipping: no hosts matched
 [WARNING]: Could not match supplied host pattern, ignoring: mcafee-win


PLAY [McAfee VSCL provisioning (Windows)] **********************************************************************************************************************************************
2019-05-29T05:32:26.967146 (delta: 0.001343)         elapsed: 44.737899 ******* 
=============================================================================== 
skipping: no hosts matched
 [WARNING]: Could not match supplied host pattern, ignoring: static-analyzer


PLAY [StaticAnalyzer provisioning] *****************************************************************************************************************************************************
2019-05-29T05:32:26.968315 (delta: 0.001153)         elapsed: 44.739068 ******* 
=============================================================================== 
skipping: no hosts matched
 [WARNING]: Could not match supplied host pattern, ignoring: virustotal


PLAY [VirusTotal provisioning] *********************************************************************************************************************************************************
2019-05-29T05:32:26.969596 (delta: 0.001268)         elapsed: 44.740349 ******* 
=============================================================================== 
skipping: no hosts matched

PLAY [AVG provisioning] ****************************************************************************************************************************************************************
2019-05-29T05:32:26.971249 (delta: 0.001641)         elapsed: 44.742002 ******* 
=============================================================================== 
 [WARNING]: Could not match supplied host pattern, ignoring: bitdefender


PLAY [AVG provisioning] ****************************************************************************************************************************************************************
2019-05-29T05:32:26.974535 (delta: 0.003272)         elapsed: 44.745288 ******* 
=============================================================================== 
skipping: no hosts matched

PLAY [EScan provisioning] **************************************************************************************************************************************************************
2019-05-29T05:32:26.976151 (delta: 0.001604)         elapsed: 44.746904 ******* 
=============================================================================== 
 [WARNING]: Could not match supplied host pattern, ignoring: virusblokada


PLAY [VirusBlokAda] ********************************************************************************************************************************************************************
2019-05-29T05:32:26.979558 (delta: 0.003392)         elapsed: 44.750311 ******* 
=============================================================================== 
skipping: no hosts matched
 [WARNING]: Could not match supplied host pattern, ignoring: zoner


PLAY [Zoner provisioning] **************************************************************************************************************************************************************
2019-05-29T05:32:26.980616 (delta: 0.001042)         elapsed: 44.751369 ******* 
=============================================================================== 
skipping: no hosts matched
 [WARNING]: Could not match supplied host pattern, ignoring: drweb


PLAY [DrWeb provisioning] **************************************************************************************************************************************************************
2019-05-29T05:32:26.981674 (delta: 0.001044)         elapsed: 44.752427 ******* 
=============================================================================== 
skipping: no hosts matched
 [WARNING]: Could not match supplied host pattern, ignoring: avast


PLAY [Avast provisioning] **************************************************************************************************************************************************************
2019-05-29T05:32:26.982700 (delta: 0.001011)         elapsed: 44.753453 ******* 
=============================================================================== 
skipping: no hosts matched

PLAY [FSecure provisioning] ************************************************************************************************************************************************************
2019-05-29T05:32:26.984355 (delta: 0.00164)         elapsed: 44.755108 ******** 
=============================================================================== 
 [WARNING]: Could not match supplied host pattern, ignoring: kaspersky


PLAY [Kaspersky provisioning] **********************************************************************************************************************************************************
2019-05-29T05:32:26.988544 (delta: 0.004161)         elapsed: 44.759297 ******* 
=============================================================================== 
skipping: no hosts matched

PLAY [TrID provisioning] ***************************************************************************************************************************************************************
2019-05-29T05:32:26.990129 (delta: 0.001572)         elapsed: 44.760882 ******* 
=============================================================================== 

PLAY [PEiD provisioning] ***************************************************************************************************************************************************************
2019-05-29T05:32:26.994418 (delta: 0.004276)         elapsed: 44.765171 ******* 
=============================================================================== 

PLAY [Unarchiver provisioning] *********************************************************************************************************************************************************
2019-05-29T05:32:26.998881 (delta: 0.004451)         elapsed: 44.769634 ******* 
=============================================================================== 
 [WARNING]: Could not match supplied host pattern, ignoring: fprot


PLAY [F-prot provisioning] *************************************************************************************************************************************************************
2019-05-29T05:32:27.001531 (delta: 0.002632)         elapsed: 44.772284 ******* 
=============================================================================== 
skipping: no hosts matched
 [WARNING]: Could not match supplied host pattern, ignoring: emsisoft-win


PLAY [Emsisoft a2cmd provisioning] *****************************************************************************************************************************************************
2019-05-29T05:32:27.002538 (delta: 0.000991)         elapsed: 44.773291 ******* 
=============================================================================== 
skipping: no hosts matched

PLAY [Unarchiver provisioning] *********************************************************************************************************************************************************
2019-05-29T05:32:27.004038 (delta: 0.001487)         elapsed: 44.774791 ******* 
=============================================================================== 

PLAY [LIEF provisioning] ***************************************************************************************************************************************************************
2019-05-29T05:32:27.007057 (delta: 0.003005)         elapsed: 44.77781 ******** 
=============================================================================== 
 [WARNING]: Could not match supplied host pattern, ignoring: dummy


PLAY [Dummy provisionning] *************************************************************************************************************************************************************
2019-05-29T05:32:27.009020 (delta: 0.00195)         elapsed: 44.779773 ******** 
=============================================================================== 
skipping: no hosts matched

PLAY [all] *****************************************************************************************************************************************************************************
2019-05-29T05:32:27.010730 (delta: 0.001697)         elapsed: 44.781483 ******* 
=============================================================================== 

TASK [Check ansible version] ***********************************************************************************************************************************************************
2019-05-29T05:32:27.017906 (delta: 0.007163)         elapsed: 44.788659 ******* 
ok: [localhost -> localhost] => {
    "changed": false, 
    "msg": "All assertions passed"
}

PLAY [Avast update] ********************************************************************************************************************************************************************
2019-05-29T05:32:27.038162 (delta: 0.02024)         elapsed: 44.808915 ******** 
=============================================================================== 
skipping: no hosts matched

PLAY [AVG update] **********************************************************************************************************************************************************************
2019-05-29T05:32:27.040077 (delta: 0.001887)         elapsed: 44.81083 ******** 
=============================================================================== 

PLAY [Bitdefender update] **************************************************************************************************************************************************************
2019-05-29T05:32:27.042037 (delta: 0.001948)         elapsed: 44.81279 ******** 
=============================================================================== 
skipping: no hosts matched

PLAY [ClamAV update] *******************************************************************************************************************************************************************
2019-05-29T05:32:27.043602 (delta: 0.001552)         elapsed: 44.814355 ******* 
=============================================================================== 

PLAY [ComodoCAVL update] ***************************************************************************************************************************************************************
2019-05-29T05:32:27.046602 (delta: 0.002988)         elapsed: 44.817355 ******* 
=============================================================================== 

PLAY [DrWeb update] ********************************************************************************************************************************************************************
2019-05-29T05:32:27.048654 (delta: 0.002035)         elapsed: 44.819407 ******* 
=============================================================================== 
skipping: no hosts matched

PLAY [Emsisoft a2cmd update (Windows)] *************************************************************************************************************************************************
2019-05-29T05:32:27.049622 (delta: 0.000949)         elapsed: 44.820375 ******* 
=============================================================================== 
skipping: no hosts matched

PLAY [EScan update] ********************************************************************************************************************************************************************
2019-05-29T05:32:27.051441 (delta: 0.001803)         elapsed: 44.822194 ******* 
=============================================================================== 

PLAY [EsetFileSecurity update] *********************************************************************************************************************************************************
2019-05-29T05:32:27.053630 (delta: 0.002169)         elapsed: 44.824383 ******* 
=============================================================================== 
skipping: no hosts matched

PLAY [F-prot update] *******************************************************************************************************************************************************************
2019-05-29T05:32:27.054419 (delta: 0.000773)         elapsed: 44.825172 ******* 
=============================================================================== 
skipping: no hosts matched

PLAY [FSecure update] ******************************************************************************************************************************************************************
2019-05-29T05:32:27.055893 (delta: 0.001449)         elapsed: 44.826646 ******* 
=============================================================================== 

PLAY [Kaspersky update (Linux)] ********************************************************************************************************************************************************
2019-05-29T05:32:27.057637 (delta: 0.001729)         elapsed: 44.82839 ******** 
=============================================================================== 
skipping: no hosts matched

PLAY [McAfee VSCL update] **************************************************************************************************************************************************************
2019-05-29T05:32:27.058648 (delta: 0.000986)         elapsed: 44.829401 ******* 
=============================================================================== 
skipping: no hosts matched

PLAY [McAfee VSCL update (Windows)] ****************************************************************************************************************************************************
2019-05-29T05:32:27.059442 (delta: 0.000778)         elapsed: 44.830195 ******* 
=============================================================================== 
skipping: no hosts matched

PLAY [PEiD update] *********************************************************************************************************************************************************************
2019-05-29T05:32:27.061109 (delta: 0.001651)         elapsed: 44.831862 ******* 
=============================================================================== 

PLAY [Sophos update] *******************************************************************************************************************************************************************
2019-05-29T05:32:27.063424 (delta: 0.00229)         elapsed: 44.834177 ******** 
=============================================================================== 
skipping: no hosts matched

PLAY [TrID update] *********************************************************************************************************************************************************************
2019-05-29T05:32:27.065277 (delta: 0.001825)         elapsed: 44.83603 ******** 
=============================================================================== 

PLAY [Virusblokada update] *************************************************************************************************************************************************************
2019-05-29T05:32:27.067166 (delta: 0.001874)         elapsed: 44.837919 ******* 
=============================================================================== 
skipping: no hosts matched

PLAY [Zoner update] ********************************************************************************************************************************************************************
2019-05-29T05:32:27.068005 (delta: 0.000814)         elapsed: 44.838758 ******* 
=============================================================================== 
skipping: no hosts matched

PLAY [all] *****************************************************************************************************************************************************************************
2019-05-29T05:32:27.069600 (delta: 0.001571)         elapsed: 44.840353 ******* 
=============================================================================== 

TASK [Check ansible version] ***********************************************************************************************************************************************************
2019-05-29T05:32:27.077148 (delta: 0.007532)         elapsed: 44.847901 ******* 
ok: [localhost -> localhost] => {
    "changed": false, 
    "msg": "All assertions passed"
}

PLAY [Packaging source code archive] ***************************************************************************************************************************************************
2019-05-29T05:32:27.097417 (delta: 0.020254)         elapsed: 44.86817 ******** 
=============================================================================== 

PLAY [Common deployment] ***************************************************************************************************************************************************************
2019-05-29T05:32:27.101148 (delta: 0.003694)         elapsed: 44.871901 ******* 
=============================================================================== 

PLAY [Frontend deployment] *************************************************************************************************************************************************************
2019-05-29T05:32:27.106690 (delta: 0.005524)         elapsed: 44.877443 ******* 
=============================================================================== 

PLAY [Brain deployment] ****************************************************************************************************************************************************************
2019-05-29T05:32:27.113328 (delta: 0.006623)         elapsed: 44.884081 ******* 
=============================================================================== 

PLAY [Probe deployment] ****************************************************************************************************************************************************************
2019-05-29T05:32:27.117125 (delta: 0.003782)         elapsed: 44.887878 ******* 
=============================================================================== 

PLAY RECAP *****************************************************************************************************************************************************************************
brain.irma                 : ok=0    changed=0    unreachable=1    failed=0   
localhost                  : ok=3    changed=0    unreachable=0    failed=0   

2019-05-29T05:32:27.118715 (delta: 0.001578)         elapsed: 44.889468 ******* 
===============================================================================`

**Comment by ch0k0bn** [comment]
the important part is this one:

> 172.16.1.30 port 22: Connection timed out

could you check that the vm has still the correct ip configured?
vm should have 2 interfaces:
- NAT for internet connection
- private network 172.16.1.30

did you start from scratch with vagrant or with the ova?

**Comment by shellchocolat** [comment]
Indeed the private network was not up anymore. 
After launching: vagrant up again: 
private network: OK
NAT: OK

but i still get an error: 
fatal: [brain.irma]: FAILED! => {"changed": false, "msg": "Failed to update apt cache."}

Full logs:
[+] Ansible vars written to /tmp/tmpdJPGVg/vars.yml
[+] Ansible inventory written to /tmp/tmpdJPGVg/inventory
[+] launching ansible-galaxy
- changing role ANXS.postgresql from cec55c974e6020044ef908e2acca9377d470b473 to cec55c974e6020044ef908e2acca9377d470b473
- extracting ANXS.postgresql to /home/raton/irma/ansible/roles/ANXS.postgresql
- ANXS.postgresql (cec55c974e6020044ef908e2acca9377d470b473) was installed successfully
- changing role franklinkim.sudo from 1.6.1 to 1.6.1
- extracting franklinkim.sudo to /home/raton/irma/ansible/roles/franklinkim.sudo
- franklinkim.sudo (1.6.1) was installed successfully
- changing role franklinkim.ufw from 1.6.0 to 1.6.0
- extracting franklinkim.ufw to /home/raton/irma/ansible/roles/franklinkim.ufw
- franklinkim.ufw (1.6.0) was installed successfully
- changing role jdauphant.nginx from v2.7.4 to v2.7.4
- extracting jdauphant.nginx to /home/raton/irma/ansible/roles/jdauphant.nginx
- jdauphant.nginx (v2.7.4) was installed successfully
- changing role Mayeu.RabbitMQ from 30ba105a753bb21eed07c8fa4b2635ff297b54b9 to 30ba105a753bb21eed07c8fa4b2635ff297b54b9
- extracting Mayeu.RabbitMQ to /home/raton/irma/ansible/roles/Mayeu.RabbitMQ
- Mayeu.RabbitMQ (30ba105a753bb21eed07c8fa4b2635ff297b54b9) was installed successfully
- changing role mivok0.users from v1.2.4 to v1.2.4
- extracting mivok0.users to /home/raton/irma/ansible/roles/mivok0.users
- mivok0.users (v1.2.4) was installed successfully
- changing role willshersystems.sshd from v0.4.7 to v0.4.7
- extracting willshersystems.sshd to /home/raton/irma/ansible/roles/willshersystems.sshd
- willshersystems.sshd (v0.4.7) was installed successfully
[+] launching ansible-playbook
[DEPRECATION WARNING]: The use of 'include' for tasks has been deprecated. Use 'import_tasks' for static inclusions or 'include_tasks' for dynamic inclusions. This feature will be 
removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: include is kept for backwards compatibility but usage is discouraged. The module documentation details page may explain more about this rationale.. This feature
 will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

PLAY [all] *****************************************************************************************************************************************************************************
2019-06-03T09:34:24.485840 (delta: 0.006732)         elapsed: 0.006732 ******** 
=============================================================================== 

TASK [Check ansible version] ***********************************************************************************************************************************************************
2019-06-03T09:34:24.513445 (delta: 0.027578)         elapsed: 0.034337 ******** 
ok: [localhost -> localhost] => {
    "changed": false, 
    "msg": "All assertions passed"
}
 [WARNING]: Could not match supplied host pattern, ignoring: windows


PLAY [Common tasks to execute on all Linux servers] ************************************************************************************************************************************
2019-06-03T09:34:24.539273 (delta: 0.025788)         elapsed: 0.060165 ******** 
=============================================================================== 

TASK [quarkslab.apt : Check Apt last update] *******************************************************************************************************************************************
2019-06-03T09:34:24.607883 (delta: 0.068565)         elapsed: 0.128775 ******** 
ok: [brain.irma]

TASK [quarkslab.apt : Update Apt if needed] ********************************************************************************************************************************************
2019-06-03T09:34:25.623804 (delta: 1.015884)         elapsed: 1.144696 ******** 
fatal: [brain.irma]: FAILED! => {"changed": false, "msg": "Failed to update apt cache."}

PLAY RECAP *****************************************************************************************************************************************************************************
brain.irma                 : ok=1    changed=0    unreachable=0    failed=1   
localhost                  : ok=1    changed=0    unreachable=0    failed=0   

2019-06-03T09:34:31.138688 (delta: 5.514851)         elapsed: 6.65958 ********* 
===============================================================================

**Comment by squared-wheel** [comment]
up

**Comment by ch0k0bn** [comment]
Will be hard to remotely debug as it is an apt problem inside your vm. If you ssh into the vm and manually try to update apt, doest this work?
Are you behind a proxy?

**Comment by squared-wheel** [comment]
I am not inside a VM, and the OS is an ubuntu 18.04 x64 ... Nevermind, i will find a way. Thanks for your help
