### ISSUE TITLE
Unable to connect to http://172.16.1.30/

### ISSUE THREAD

**Issue by cuckoo-linux** [quarkslab/irma#66]
I installed irma using these commands:
$ git clone https://github.com/quarkslab/irma
$ cd /irma/ansible
$ vagrant up
Installation is completed successfully but cant open web interface,kindly help.

**Comment by cuckoo-linux** [comment]
After that when i tried to run these commands:
 pip install -r requirements.txt
python irma-ansible.py environments/allinone_dev.yml playbooks/playbook.yml
**python: can't open file 'irma-ansible.py': [Errno 2] No such file or directory**
although irma-ansible is present in directory.

**Comment by ch0k0bn** [comment]
make sure you have cloned with `--recursive` option to also clone irma-ansible submodule (check if the irma/ansible/irma-ansible/irma-ansible.py is present

**Comment by cuckoo-linux** [comment]
yup its present,i checked it.
/home/user/Pictures/Screenshot from 2019-12-19 16-31-02.png
