### ISSUE TITLE
Public IP

### ISSUE THREAD

**Issue by emaragkos** [quarkslab/irma#73]
Hey there, I am interested in hosting this on a VPS in order to be accessible from everywhere from a public IP. Is this possible to and if so, how?

**Comment by ch0k0bn** [comment]
Hey,

It is possible:

* you will have to setup your VPS to be VM+ansible-ready (install vagrant, vagrant-libvirt plugin, kvm/qemu, libvirt, ansible)
* download (latest_version)[https://github.com/quarkslab/irma/releases/download/v2.4.14-oss/core-v2.4.14-oss.zip] archive
* in `ansible/environments` directory, create an environment file (copy and amend [prod.yml](https://github.com/quarkslab/irma/blob/master/ansible/environments/prod.yml) with the number and settings of each VM)
* make sure you add the correct version variable like in `demo.yml` environment see [here](https://github.com/quarkslab/irma/blob/master/ansible/environments/demo.yml#L14)
* Start Vms: `VM_ENV=<your_env_file_without_extension> vagrant up --provider=libvirt`
* Launch [full install](https://irma.readthedocs.io/en/latest/install/automated/ansible.html#launch-ansible)

That is just basic Irma install up to here, then to expose it publicly either:
* you do a port forward from VPS ports 80+443 to frontend VM ports 80+443
* or you setup an nginx as proxy_pass to the frontend VM nginx, something like:
```
   location / {
       proxy_pass https://<frontend_vm_ip>:443;
    }
```
