### ISSUE TITLE
Query on installation process

### ISSUE THREAD

**Issue by solveryn91** [quarkslab/irma#74]
Hi, i am interested with this framework to be installed for educational purposes but I am not experienced in Linux. I am currently installing on a Ubuntu 20.04 LTS in VirtualBox, as in allinone_dev. 

My installation process came to a halt when I attempted to run the following command:

python3 irma-ansible.py environments/allinone_dev.yml playbooks/playbook.yml

[install_log.txt](https://github.com/quarkslab/irma/files/5966628/install_log.txt)

Attached with an install log where the error indicates, and I would like to know how to resolve it.

Thank you.

**Comment by ch0k0bn** [comment]
Need to investigate this issue, I reproduced it also locally. I guess at the time of v2 we were mainly using python2 for ansible and the different behaviour comes from here, now we are using python3 but with a different version of Ansible (2.8.12 now vs 2.7.12).

As a temporary workaround, could you try using python2 for the irma-ansible command ?

Btw I just added a fix in master for a deprecated url for get-pip.

**Comment by solveryn91** [comment]
Thanks for the reply.

So yea I ran with python2 after obtaining the fix , hinted me with missing libraries. Had yaml settled. Then something shown up:

ImportError: No module named ansible.cli.galaxy

So far checked with pip install ansible, hinted me that installation requirements already satisfied.  Not sure if it was a part from ansible, or my fresh Ubuntu machine..

**Comment by ch0k0bn** [comment]
Could you try inside a python2 virtualenv:

```bash
# if needed
$ sudo apt install virtualenv
# create a python2 venv
$ virtualenv -p python2 venv
# activate it
$ source venv2/bin/activate
# install dependencies
$ cd <irma_folder>/ansible
$ pip install -r requirements.txt
# Then launch install
$ python irma-ansible.py environments/allinone_dev.yml playbooks/playbook.yml
```

**Comment by solveryn91** [comment]
Allrite installing as intended, cheers :)
The installation went hours so far no problem.

**Comment by ch0k0bn** [comment]
good to know! :+1:
